[theme]
# The main accent color (The Copenhagenize Sky Blue from the brochure cover)
primaryColor = "#1BBBEC"

# The main background of the app
backgroundColor = "#ffffff"

# The background of the sidebar and secondary text boxes
secondaryBackgroundColor = "#f4f6f9"

# The color of the text
textColor = "#1e1e1e"

# The font family 
font = "tt norms"